package main.java.model;
// Generated Apr 15, 2017 9:17:45 PM by Hibernate Tools 4.3.1



/**
 * Account generated by hbm2java
 */
public class Account implements java.io.Serializable {


     private String usrName;
     private String passWrd;
     private Boolean isTheFisrtTime;

    public Account() {
    }

	
    public Account(String usrName) {
        this.usrName = usrName;
    }
    public Account(String usrName, String passWrd, Boolean isTheFisrtTime) {
       this.usrName = usrName;
       this.passWrd = passWrd;
       this.isTheFisrtTime = isTheFisrtTime;
    }
   
    public String getUsrName() {
        return this.usrName;
    }
    
    public void setUsrName(String usrName) {
        this.usrName = usrName;
    }
    public String getPassWrd() {
        return this.passWrd;
    }
    
    public void setPassWrd(String passWrd) {
        this.passWrd = passWrd;
    }
    public Boolean getIsTheFisrtTime() {
        return this.isTheFisrtTime;
    }
    
    public void setIsTheFisrtTime(Boolean isTheFisrtTime) {
        this.isTheFisrtTime = isTheFisrtTime;
    }




}


