package main.java.model;
// Generated Apr 11, 2017 10:02:26 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Student generated by hbm2java
 */
public class Student  implements java.io.Serializable {


     private String studentId;
     private String studentName;
     private String usrName;
     private String className;
     private String sex;
     private Date dob;
     private String address;
     private Set classsubjects = new HashSet(0);
     private Set attendances = new HashSet(0);

    public Student() {
    }

	
    public Student(String studentId) {
        this.studentId = studentId;
    }
    public Student(String studentId, String studentName, String usrName, String className, String sex, Date dob, String address, Set classsubjects, Set attendances) {
       this.studentId = studentId;
       this.studentName = studentName;
       this.usrName = usrName;
       this.className = className;
       this.sex = sex;
       this.dob = dob;
       this.address = address;
       this.classsubjects = classsubjects;
       this.attendances = attendances;
    }
   
    public String getStudentId() {
        return this.studentId;
    }
    
    public void setStudentId(String studentId) {
        this.studentId = studentId;
    }
    public String getStudentName() {
        return this.studentName;
    }
    
    public void setStudentName(String studentName) {
        this.studentName = studentName;
    }
    public String getUsrName() {
        return this.usrName;
    }
    
    public void setUsrName(String usrName) {
        this.usrName = usrName;
    }
    public String getClassName() {
        return this.className;
    }
    
    public void setClassName(String className) {
        this.className = className;
    }
    public String getSex() {
        return this.sex;
    }
    
    public void setSex(String sex) {
        this.sex = sex;
    }
    public Date getDob() {
        return this.dob;
    }
    
    public void setDob(Date dob) {
        this.dob = dob;
    }
    public String getAddress() {
        return this.address;
    }
    
    public void setAddress(String address) {
        this.address = address;
    }
    public Set getClasssubjects() {
        return this.classsubjects;
    }
    
    public void setClasssubjects(Set classsubjects) {
        this.classsubjects = classsubjects;
    }
    public Set getAttendances() {
        return this.attendances;
    }
    
    public void setAttendances(Set attendances) {
        this.attendances = attendances;
    }




}


