package main.java.model;
// Generated Apr 15, 2017 9:17:45 PM by Hibernate Tools 4.3.1



/**
 * StudentSubject generated by hbm2java
 */
public class StudentSubject  implements java.io.Serializable {
     private StudentSubjectId id;
     private ClassSubject classsubject;
     private Student student;
     private String note;

    public StudentSubject() {
    }

	
    public StudentSubject(StudentSubjectId id, ClassSubject classsubject, Student student) {
        this.id = id;
        this.classsubject = classsubject;
        this.student = student;
    }
    public StudentSubject(StudentSubjectId id, ClassSubject classsubject, Student student, String note) {
       this.id = id;
       this.classsubject = classsubject;
       this.student = student;
       this.note = note;
    }
   
    public StudentSubjectId getId() {
        return this.id;
    }
    
    public void setId(StudentSubjectId id) {
        this.id = id;
    }
    public ClassSubject getClasssubject() {
        return this.classsubject;
    }
    
    public void setClasssubject(ClassSubject classsubject) {
        this.classsubject = classsubject;
    }
    public Student getStudent() {
        return this.student;
    }
    
    public void setStudent(Student student) {
        this.student = student;
    }
    public String getNote() {
        return this.note;
    }
    
    public void setNote(String note) {
        this.note = note;
    }
}


