package main.java.model;
// Generated Apr 15, 2017 9:17:45 PM by Hibernate Tools 4.3.1



/**
 * Teacher generated by hbm2java
 */
public class Teacher  implements java.io.Serializable {


     private String teacherId;
     private String teacherName;
     private String usrName;

    public Teacher() {
    }

	
    public Teacher(String teacherId) {
        this.teacherId = teacherId;
    }
    public Teacher(String teacherId, String teacherName, String usrName) {
       this.teacherId = teacherId;
       this.teacherName = teacherName;
       this.usrName = usrName;
    }
   
    public String getTeacherId() {
        return this.teacherId;
    }
    
    public void setTeacherId(String teacherId) {
        this.teacherId = teacherId;
    }
    public String getTeacherName() {
        return this.teacherName;
    }
    
    public void setTeacherName(String teacherName) {
        this.teacherName = teacherName;
    }
    public String getUsrName() {
        return this.usrName;
    }
    
    public void setUsrName(String usrName) {
        this.usrName = usrName;
    }




}


