package main.java.model;
// Generated Apr 11, 2017 10:02:26 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Timetable generated by hbm2java
 */
public class Timetable  implements java.io.Serializable {


     private String timeTableId;
     private ClassSubject classsubject;
     private Date startDate;
     private Date endDate;
     private Integer weekCount;
     private String weekDay;
     private Date startTime;
     private Date endTime;
     private String classRoom;

    public Timetable() {
    }

	
    public Timetable(String timeTableId) {
        this.timeTableId = timeTableId;
    }
    public Timetable(String timeTableId, ClassSubject classsubject, Date startDate, Date endDate, Integer weekCount, String weekDay, Date startTime, Date endTime, String classRoom) {
       this.timeTableId = timeTableId;
       this.classsubject = classsubject;
       this.startDate = startDate;
       this.endDate = endDate;
       this.weekCount = weekCount;
       this.weekDay = weekDay;
       this.startTime = startTime;
       this.endTime = endTime;
       this.classRoom = classRoom;
    }
   
    public String getTimeTableId() {
        return this.timeTableId;
    }
    
    public void setTimeTableId(String timeTableId) {
        this.timeTableId = timeTableId;
    }
    public ClassSubject getClasssubject() {
        return this.classsubject;
    }
    
    public void setClasssubject(ClassSubject classsubject) {
        this.classsubject = classsubject;
    }
    public Date getStartDate() {
        return this.startDate;
    }
    
    public void setStartDate(Date startDate) {
        this.startDate = startDate;
    }
    public Date getEndDate() {
        return this.endDate;
    }
    
    public void setEndDate(Date endDate) {
        this.endDate = endDate;
    }
    public Integer getWeekCount() {
        return this.weekCount;
    }
    
    public void setWeekCount(Integer weekCount) {
        this.weekCount = weekCount;
    }
    public String getWeekDay() {
        return this.weekDay;
    }
    
    public void setWeekDay(String weekDay) {
        this.weekDay = weekDay;
    }
    public Date getStartTime() {
        return this.startTime;
    }
    
    public void setStartTime(Date startTime) {
        this.startTime = startTime;
    }
    public Date getEndTime() {
        return this.endTime;
    }
    
    public void setEndTime(Date endTime) {
        this.endTime = endTime;
    }
    public String getClassRoom() {
        return this.classRoom;
    }
    
    public void setClassRoom(String classRoom) {
        this.classRoom = classRoom;
    }




}


